### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by jtom2388** [andy-h-2016/memory_cache#4]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by andy-h-2016** [comment]
Are there issues with the constraints or formatting? The subpoints are checked off but the parent points are not.

**Comment by jtom2388** [comment]
No issues with format or constraints, just reviewing overall structure of schema

**Comment by andy-h-2016** [comment]
Thanks for the clarification. So would I be able to check off "Contains appropriate constraints/details" and "Correctly formatted" and close out this issue?

**Comment by jtom2388** [comment]
Don't close it just yet. I want to review it and maybe discuss it with you if I think something can be changed. Otherwise I'll close it myself
