### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by jtom2388** [andy-h-2016/memory_cache#5]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by jtom2388** [comment]
MVP list looks good. You just need to fix a slight format issue. MVP #1 and #2 are on the same line.

**Comment by andy-h-2016** [comment]
Thanks for catching that Jordan!
